os: osx
osx_image: xcode10.3
sudo: true
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - /Users/travis/build/SCCapstone/FaceCheck/FaceCheckApp/node_modules
# Moving to react-native project directory
before_install:
  - cd FaceCheckApp
# Installing npm packages
install:
  - npm install
# Linting and running tests
script:
  - npm run lint
  - npm test